### ISSUE TITLE
How to remove horizontal lines in multiline equations

### ISSUE THREAD

**Issue by sohagan1** [vlmantova/bookml#39]
By creating a `bmluser` folder containing a `.css` file, I've been able to remove top and bottom borders in displayed equations.

`.ltx_equation.ltx_eqn_div {
  border-top: none;
  border-bottom: none;
}`

I would also like to remove borders on table rows in multiline equations, but can't get this to work.

Naively, I tried

`.ltx_equation.ltx_eqn_row {
  border-top: none;
  border-bottom: none;
}`

but this has no effect.

**Comment by xworld21** [comment]
> I would also like to remove borders on table rows in multiline equations, but can't get this to work.

Can you please show me which environment you are using (e.g. multline*, align, ...)?

Different environments generate slightly different HTML markup, typically with tables. bookdown will then add its own borders and colour banding. You'll need to write a CSS selector that is at least as specific as the bookdown one in order to disable the borders.

**Comment by sohagan1** [comment]
For example:

```
\begin{align*}
    \norm{\vect{e}_k}_p &= \norm{\mat{R}^k \vect{e}_0}_p \\
    &\leqslant \norm{\mat{R}^k}_p \norm{\vect{e}_0}_p \\
    &\leqslant \norm{\mat{R}}_p^k \norm{\vect{e}_0}_p 
\end{align*}
```

**Comment by xworld21** [comment]
The following should be enough to beat bookdown's very specific CSS:
```css
.book .book-body .page-wrapper .page-inner section.normal table.ltx_equationgroup tr,
.book .book-body .page-wrapper .page-inner section.normal table.ltx_equationgroup tr th,
.book .book-body .page-wrapper .page-inner section.normal table.ltx_equationgroup tr td {
  border-top-width: 0;
  border-bottom-width: 0;
}
```

Closing the issue, but feel free to reopen if this is not enough.
